import React,{useState} from 'react';
import {Alert,Image,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {CameraView,useCameraPermissions} from 'expo-camera';
import {resources,messageOf,fileUrl} from '../data/api';
import {colors} from '../theme';

export default function ScannerScreen({navigation}:any){
 const [permission,requestPermission]=useCameraPermissions();const [scanned,setScanned]=useState(false);const [result,setResult]=useState<any>(null);
 if(!permission)return <View style={s.center}><Text>Solicitando cámara…</Text></View>;
 if(!permission.granted)return <View style={s.center}><Text style={{textAlign:'center',marginBottom:15}}>Necesitamos acceso a la cámara para escanear el carnet QR.</Text><TouchableOpacity style={s.btn} onPress={requestPermission}><Text style={s.bt}>PERMITIR CÁMARA</Text></TouchableOpacity></View>;
 const scan=async({data}:any)=>{if(scanned)return;setScanned(true);try{const r=await resources.scan(data);setResult(r.data);Alert.alert('SENA PARKING',r.data?.message||'Movimiento registrado')}catch(e){setResult({error:messageOf(e)});Alert.alert('Error',messageOf(e))}};
 return <View style={{flex:1,backgroundColor:'#000'}}>{!result?<><CameraView style={{flex:1}} facing="back" barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={scanned?undefined:scan}/><View style={s.overlay}><Text style={s.title}>ESCANEAR CARNET</Text><View style={s.square}/><Text style={s.hint}>Centra el código QR dentro del recuadro</Text><TouchableOpacity style={s.btn} onPress={()=>setScanned(false)}><Text style={s.bt}>ESCANEAR DE NUEVO</Text></TouchableOpacity><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>Volver</Text></TouchableOpacity></View></>:<ScrollView contentContainerStyle={s.resultPage}><Text style={s.resultTitle}>Carnet validado</Text>{result.error?<Text style={s.error}>{result.error}</Text>:<><View style={s.card}>{result.user?.foto&&<Image source={{uri:fileUrl(result.user.foto)}} style={s.photo}/>}<Text style={s.name}>{result.user?.nombres} {result.user?.apellidos}</Text><Text>Documento: {result.user?.documento||'—'}</Text><Text>Ficha: {result.user?.ficha||'—'}</Text><Text>Centro: {result.user?.centroFormacion?.nombre||'—'}</Text><Text style={s.state}>{result.estado==='dentro'?'🟢 Entrada registrada':'⚪ Salida registrada'}</Text></View>{result.vehiculo&&<View style={s.card}><Text style={s.cardTitle}>Vehículo</Text>{result.vehiculo.foto_principal&&<Image source={{uri:fileUrl(result.vehiculo.foto_principal)}} style={s.vehiclePhoto}/>}<Text>Tipo: {result.vehiculo.tipo||'—'}</Text><Text>Marca: {result.vehiculo.marca||'—'}</Text><Text>Color: {result.vehiculo.color||'—'}</Text>{result.vehiculo.placa&&<Text>Placa: {result.vehiculo.placa}</Text>}{result.vehiculo.serial&&<Text>Serial: {result.vehiculo.serial}</Text>}</View>}<View style={s.card}><Text style={s.cardTitle}>Movimiento</Text><Text>{result.message}</Text><Text>Fecha: {result.registro?.fecha||'—'}</Text><Text>Entrada: {result.registro?.hora_entrada?new Date(result.registro.hora_entrada).toLocaleString('es-CO'):'—'}</Text><Text>Salida: {result.registro?.hora_salida?new Date(result.registro.hora_salida).toLocaleString('es-CO'):'—'}</Text></View></>}<TouchableOpacity style={s.btn} onPress={()=>{setResult(null);setScanned(false)}}><Text style={s.bt}>ESCANEAR OTRO CARNET</Text></TouchableOpacity><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.backDark}>Volver</Text></TouchableOpacity></ScrollView>}</View>
}
const s=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center',padding:25},overlay:{...StyleSheet.absoluteFillObject,alignItems:'center',justifyContent:'center',padding:25},title:{color:'#fff',fontSize:24,fontWeight:'900',marginBottom:25},square:{width:260,height:260,borderWidth:3,borderColor:'#fff',borderRadius:20},hint:{color:'#fff',marginTop:20,textAlign:'center'},btn:{backgroundColor:colors.primary,padding:14,borderRadius:10,marginTop:20,alignItems:'center'},bt:{color:'#fff',fontWeight:'900'},back:{color:'#fff',fontWeight:'800',marginTop:15},resultPage:{padding:20,backgroundColor:colors.bg,flexGrow:1},resultTitle:{fontSize:27,fontWeight:'900',color:colors.dark,marginBottom:15},card:{backgroundColor:'#fff',borderRadius:16,padding:18,marginBottom:14,borderWidth:1,borderColor:colors.border},photo:{width:120,height:150,borderRadius:12,alignSelf:'center',marginBottom:12},vehiclePhoto:{width:'100%',height:180,borderRadius:12,marginBottom:10},name:{fontSize:22,fontWeight:'900',color:colors.dark,marginBottom:8,textAlign:'center'},state:{fontWeight:'900',color:colors.dark,marginTop:10},cardTitle:{fontSize:18,fontWeight:'900',color:colors.dark,marginBottom:8},error:{backgroundColor:'#FFEBEE',padding:14,borderRadius:10,color:colors.danger},backDark:{color:colors.dark,fontWeight:'900',textAlign:'center',marginTop:15}})
